USE [master]


DECLARE @dbname NVARCHAR(128) = 'MailReader';
IF NOT EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE ('[' + name + ']' = @dbname OR name = @dbname))
BEGIN
	CREATE DATABASE [MailReader]
	 CONTAINMENT = NONE
	 ON  PRIMARY 
	( NAME = N'MailReader', FILENAME = N'%MDF_PATH%' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
	 LOG ON 
	( NAME = N'MailReader_log', FILENAME = N'%LDF_PATH%' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)

	ALTER DATABASE [MailReader] SET COMPATIBILITY_LEVEL = 110

	IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
	begin
	EXEC [MailReader2].[dbo].[sp_fulltext_database] @action = 'enable'
	end

	ALTER DATABASE [MailReader] SET ANSI_NULL_DEFAULT OFF 

	ALTER DATABASE [MailReader] SET ANSI_NULLS OFF 

	ALTER DATABASE [MailReader] SET ANSI_PADDING OFF 

	ALTER DATABASE [MailReader] SET ANSI_WARNINGS OFF 

	ALTER DATABASE [MailReader] SET ARITHABORT OFF 

	ALTER DATABASE [MailReader] SET AUTO_CLOSE OFF 

	ALTER DATABASE [MailReader] SET AUTO_CREATE_STATISTICS ON 

	ALTER DATABASE [MailReader] SET AUTO_SHRINK OFF 
	

	ALTER DATABASE [MailReader] SET AUTO_UPDATE_STATISTICS ON 
	

	ALTER DATABASE [MailReader] SET CURSOR_CLOSE_ON_COMMIT OFF 
	

	ALTER DATABASE [MailReader] SET CURSOR_DEFAULT  GLOBAL 
	

	ALTER DATABASE [MailReader] SET CONCAT_NULL_YIELDS_NULL OFF 
	

	ALTER DATABASE [MailReader] SET NUMERIC_ROUNDABORT OFF 
	

	ALTER DATABASE [MailReader] SET QUOTED_IDENTIFIER OFF 
	

	ALTER DATABASE [MailReader] SET RECURSIVE_TRIGGERS OFF 
	

	ALTER DATABASE [MailReader] SET  DISABLE_BROKER 
	

	ALTER DATABASE [MailReader] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
	

	ALTER DATABASE [MailReader] SET DATE_CORRELATION_OPTIMIZATION OFF 
	

	ALTER DATABASE [MailReader] SET TRUSTWORTHY OFF 
	

	ALTER DATABASE [MailReader] SET ALLOW_SNAPSHOT_ISOLATION OFF 
	

	ALTER DATABASE [MailReader] SET PARAMETERIZATION SIMPLE 
	

	ALTER DATABASE [MailReader] SET READ_COMMITTED_SNAPSHOT OFF 
	

	ALTER DATABASE [MailReader] SET HONOR_BROKER_PRIORITY OFF 
	

	ALTER DATABASE [MailReader] SET RECOVERY FULL 
	

	ALTER DATABASE [MailReader] SET  MULTI_USER 
	

	ALTER DATABASE [MailReader] SET PAGE_VERIFY CHECKSUM  
	

	ALTER DATABASE [MailReader] SET DB_CHAINING OFF 
	

	ALTER DATABASE [MailReader] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
	

	ALTER DATABASE [MailReader] SET TARGET_RECOVERY_TIME = 0 SECONDS 
	

	ALTER DATABASE [MailReader] SET  READ_WRITE 
	
END